### PR TITLE
Update SikulixServer

### PR DESCRIPTION
**Pull request by RMizuguchi**
Reflected your advices (https://github.com/RaiMan/SikuliX1/pull/186#issuecomment-524822952) , and revised some commands.

Next, I will start working on changing of the ControlBox.

### CODE REVIEW

**Comment by balmma** [comment]
> the task-id should be a simple number beginning with 1 after server start (easier to use/remember)

Wouldn't a UUID be more appropriate for such an ID? Easy to generate and guaranteed to be unique.

**Comment by RMizuguchi** [comment]
Yes. I think too that UUID is an excellent choice.

But, I understand that simple number is easy for non-engneer user to use/remember. In fact, when I showed it to a few non-engeneer staff at work, they preferred simple number.
Since I want to use SikuliX for RPA, I think that a simple number is better for task-id.

**Comment by balmma** [comment]
What's the use case where numbers are simpler to use/remember than UUIDs? Sorry, don't really get it :-)

**Comment by balmma** [comment]
Please don't get me wrong, I can perfectly live with the simple number approach. It just has some (although very minor) drawbacks we can easily avoid using UUIDs.

**Comment by RMizuguchi** [comment]
> What's the use case where numbers are simpler to use/remember than UUIDs?

Although it is not a use case, the staff's opinions were roughly as follows:

1. Simple number are easier to communicate verbally.
2. They don't like long alphanumeric strings in the first place :(

> It just has some (although very minor) drawbacks we can easily avoid using UUIDs.

Is it a case that can be canceled with a past task-id, for example?

We might need to do that add "sequence number". 
What about using simple numbers for sequence number and UUID for task-id?

**Comment by balmma** [comment]
> Simple number are easier to communicate verbally

Why is there a need to communicate task IDs verbally? A task is a rather short living thing, not a long living test configuration. IMHO there will be rarely any need to pass a task ID (which anyway gets somewhat obsolete after the run) to a fellow team member.

> Is it a case that can be canceled with a past task-id, for example?

Yes, using this volatile, non persistent sequence there is just no way to trust the task identified by an ID. After a server restart there might me a new task with same ID as the previously started one. Sure, this might be kind of an edge case, but why taking the risk to get some questionable convenience?

> What about using simple numbers for sequence number and UUID for task-id?

I would rather stick to the simple number ID approach than introducing another identifier.

But overall I really don't want to be nitpicky here, just wanted to share my objections. The sequential number is OK, just not optimal (IMHO).

**Comment by RMizuguchi** [comment]
> Why is there a need to communicate task IDs verbally? 

Perhaps, they want to verbally indicate the specific task that failed.
I know them and can understand a little.

> But overall I really don't want to be nitpicky here, just wanted to share my objections. The sequential number is OK, just not optimal (IMHO).

I understand what you are saying well, and I think you are right.

So, I would like to ask @RaiMan for the final decision.

**Comment by balmma** [comment]
> Perhaps, they want to verbally indicate the specific task that failed.

OK, but they still can't be sure if they really talk about the SAME task :-)

> So, I would like to ask @RaiMan for the final decision.

Agreed.

**Comment by RMizuguchi** [comment]
> OK, but they still can't be sure if they really talk about the SAME task :-)

LOL
It could be the case.

**Comment by RaiMan** [comment]
Interesting discussion ;-) sorry, to be late.

IMHO:
- the standard returned ID should be a sequence number counting from the start of the server (since it is eventually to be used manually with a task command)
- I like the UUID idea and it should be implemented additionally as a unique stamp for a task to be shown/stored with history information (should eventually be made available to the script also, where it could be used in some continuous user logging).

The following I think makes sense additionally:
- /tasks/:name    --- only show entries with the given scriptname
- /tasks/:id/stop  --- abort the script

**Comment by balmma** [comment]
> /tasks/:name --- only show entries with the given scriptname

Isn't this already available with `/scripts/:name/tasks`?

**Comment by RMizuguchi** [comment]
> 
> 
> > /tasks/:name --- only show entries with the given scriptname
> 
> Isn't this already available with `/scripts/:name/tasks`?

Yes, I agree. This is it.

**Comment by RaiMan** [comment]
> Isn't this already available with /scripts/:name/tasks?

Sorry - not yet enough coffee ;-)

**Comment by RMizuguchi** [comment]
> /tasks/:id/stop --- abort the script

This takes more time than I thought.
So, I will post new PR for this.

**Comment by balmma** [comment]
> /tasks/:id/stop --- abort the script

We already have `/tasks/:id/cancel`. Wouldn't it be better to stick to this call? Remove the task from the queue if not started yet, abort the runner using its `abort()` method otherwise.

**Comment by RaiMan** [comment]
Sorry - might be a misunderstanding, but in the wiki is stated that 
`/tasks/:id/cancel` :
A controller that cancels the task with the ID (only if still queued).

... and with `/pause` it says:
(There might also come a feature to gracefully stop a running script)

... but I do not have a problem with using `/tasks/:id/cancel` to stop a running script also.

My interpretation was: stop a running script is not yet implemented.

**Comment by balmma** [comment]
I think the wiki is already a bit outdated. It was written before we implemented the abort() stuff for the runners when it was not yet possible to cancel a running script.

IMHO the `/tasks/:id/cancel` should do both, simply remove non running scripts from the queue and abort already running scripts. No need to have to separate calls for that.

**Comment by RMizuguchi** [comment]
Yes. Stop a running script is not currently implemented.
Also, `/pause` pauses after the running script finishes.

I agree that the implementation of stopping the running script is implemented in `/tasks/:id/cancel`.

**Comment by RaiMan** [comment]
> IMHO the /tasks/:id/cancel should do both, simply remove non running scripts from the queue and abort already running scripts. No need to have two separate calls for that.

agreed

I will revise the wiki about this case.

@RMizuguchi please check the wiki, since it will be the base for the docs of the server features.

**Comment by balmma** [comment]
Do we agree that `/pause`does not cancel running scripts? It's more like "pause starting new script runs".

**Comment by RaiMan** [comment]
wiki about `/pause`:
Pauses the script execution after the currently running script ends. 

Hence it should not stop a running script.

So IMHO if you would like to pause the execution of scripts, after you have stopped the running script the command sequence would be:
`/pause`
`/tasks/:id/cancel`

where `/pause` should return the information of the task, if one is running.

**Comment by balmma** [comment]
> So IMHO if you would like to pause the execution of scripts, after you have stopped the running  script the command sequence would be:
> /pause
> /tasks/:id/cancel

Not sure if `/pause` should care about running tasks at all or even return running ones.

IMHO the sequence (if you want to cancel running scripts) would rather be:
```
/pause
/tasks
for runningTask in tasks
  /task/:id/cancel
```
Another option would be to add a `cancelRunning` (or similar) parameter to the /pause call which defaults to false.

**Comment by RaiMan** [comment]
No problem.

... but I thought, that `/pause` has to wait for the running script to terminate, it has the information anyways.

... and I do not think that there is a need for an additional parameter.

**Comment by balmma** [comment]
> but I thought, that /pause has to wait for the running script to terminate, it has the information anyways.

I think `/pause` just set a "marker" that causes the server not to accept new runs. Doesn't have to wait.

> ... and I do not think that there is a need for an additional parameter.

agreed

**Comment by RaiMan** [comment]
> I think /pause just set a "marker" that causes the server not to accept new runs. Doesn't have to wait.

LOL, that was too easy --- agreed

**Pull request merged**
