### PR TITLE
[1.1.4] hotkey listener - add shutdown hook

### PR DESCRIPTION
**Pull request by myshzzx**
set hotkey listener thread daemon, and register a shutdown hook to close it when exit

### CODE REVIEW

**Comment by RaiMan** [comment]
Thanks for making me aware of the problem.

But I will not use your proposal, because shutting down the hotkey listening should be part of global shutdown, which is partly implemented and should use existing features like stop() and/or cleanUp().

I will make an extra bug for that and revise the shutdown behaviour asap.

**Comment by myshzzx** [comment]
the non daemon threads prevent jvm from closing normally.

**Comment by RaiMan** [comment]
yes thank you - understood.

... but as mentioned: I will add the removal of the threads using methods already available in the package.

**Comment by myshzzx** [comment]
```java	
public static void main(String[] args) {
	new Screen().doubleClick();
}
```
jvm will not exit normally , seems blocking in ```ScreenHighlighter.closeAll();```

**Comment by myshzzx** [comment]
win7 x64, jdk11, new build sikulixapi 1.1.4-SNAPSHOT

**Pull request closed without merging**
