### PR TITLE
Better separation of AWT and Windows keys

### PR DESCRIPTION
**Pull request by balmma**
Use proper Windows VK codes when building Windows layout (no more mixup with AWT codes).

Keys like WIN and CONTEXT should work now. ALTGR can now be used as a modifier.

### CODE REVIEW

**Comment by RaiMan** [comment]
Thanks. Will check later.

Any idea about that issue #55 
It seems it was added with the first merge of your implementation

**Comment by balmma** [comment]
I don't see any any correlation between this feature and the mentioned issue.

**Comment by RaiMan** [comment]
ok, thanks. I will later dive into it (have to reactivate my Ubuntu 18 ;-)

**Comment by RaiMan** [comment]
The Problem existed on Mac too and was caused by the new KeyboardLayout.
see the quick fix: https://github.com/RaiMan/SikuliX1/commit/013f0042b53ff905b1a9a5ed64bc5ceaf29a4f69
will check later for consequences on Windows.

**Comment by balmma** [comment]
Ok got it. There was the wrong issue mentioned in your comment :-)

Would probably be much simpler not to cache the user32 instance at all. Just use SXUser32.INSTANCE directly everywhere you use getSXUser32() now. The compiler optimizes this anyway.

**Comment by balmma** [comment]
I can confirm that it works  on Windows as well.

**Comment by balmma** [comment]
See new PR #88. Sorry for the troubles...

**Pull request merged**
