### PR TITLE
Restore minimized windows on focus

### PR DESCRIPTION
**Pull request by balmma**
Not restoring minimized windows on focus is just cumbersome. Sorry, my fault :-)

### CODE REVIEW

**Comment by RaiMan** [comment]
My God ;-) you are addressing areas where people have been complaining about for years - I love it :-)

**Comment by balmma** [comment]
I've a whole Engineering team working with SikuliX. So I get a lot of user based feedback. We are using SikuliX as a replacement for SmartBear TestComplete / TestExecute and I can say that SikuliX is superior in many areas. It solves so many problems for us, so I'm more than happy to solve some of yours :-)

**Comment by RaiMan** [comment]
Thanks for feedback. All the best for you and your team.

Are you using the scripting level (IDE with Jython) or are you using the Java API level in a Java dev environment? If this is the wrong place for such details: mail sikulix---at---outlook---dot---com

**Comment by balmma** [comment]
We are using SikuliX on the scripting level. Our engineers are creating SikuliX Scripts in the IDE, later we execute the scripts using the -r option.

**Comment by RaiMan** [comment]
Thanks for the info. All the best.

**Pull request merged**
