### PR TITLE
ServerRunner with Undertow

### PR DESCRIPTION
**Pull request by RMizuguchi**
**Feature discussion in issue #130**

Implementation of the ServerRunner with Undertow is completed.
The sequential execution is implemented with RequestLimitedHandler.
Also, this pull request is a superset of #121.

The purpose is to make a new starting point for SikulixServer
(formerly named ServerRunner/RunServer)

- Implementation with Undertow
- Add Control Box
- Refactor startRunner
- Refactor RunCommandHttpHandler
- Update query string parsing
- Rename ServerRunner to SikulixServer
- Remove "extends AbstractScriptRunner" and Move it to the support package
- Remove Eval command (This feature does not currently work)

There are other features that I would like to add, but I take a break.
And so, I am in no hurry :-)

@RaiMan @balmma 
This work was very rewarding.
Thanks for your advice!!

### CODE REVIEW

**Comment by balmma** [comment]
Wow, what a great starting point. Thank you very much.
Will happily do a deeper review later this week.

**Comment by RMizuguchi** [comment]
Thank you.
Looking forward to your review :-)

**Comment by RaiMan** [comment]
@RMizuguchi 
Thanks for now. I will also try to have a look into it during this week.

**Comment by RMizuguchi** [comment]
@RaiMan 
Thanks. I'm looking forward to it :-)
But, please don't overdo it.

**Comment by RaiMan** [comment]
@RMizuguchi 
be sure, I will not do it ;-)

**Comment by RMizuguchi** [comment]
@balmma 
I'm so happy to get many comments from you. Thanks.
I will refactor startRunner and RunCommandHttpHandler based on your comment.

But, as for query string parsing,  need to have discussion.
In my opinion, first, should make the rule of arguments same when executed with Command Run(-r) and ServerRunner(-s).
sys.argv of Command Run is order by written. While, TreeMap of QueryParameterUtils.parseQueryString is sorted by key name.
Arguments should be treated the same in the same script.

Maybe the reason that ServerRunner extends AbstractScriptRunner is because to make it easy to get command line options. 
... I want to hear RaiMan's answer.

**Comment by balmma** [comment]
> But, as for query string parsing, need to have discussion.

Yes, you are right. Then a better solution would be to just use the output from  QueryParameterUtils.parseQueryString directly as it uses a LinkedHashMap which preserves the insertion order when iterating over it or get it's values. But probably it would anyway be better to change the params syntax to something like &params=foo;bar;hello;world. IMHO this would be much clearer.

> is because to make it easy to get command line options

No, certainly not. It's just not a real ScriptRunner because it does not override any useful method of AbstractScriptRunner to run scripts. It just implements a static run method (the same goes for ProcessRunner, which is not a real ScriptRunner implementation either). This one gets only called from RunTime with no args at all.

`Runner.runScripts(RunTime.getRunScripts());`

**Comment by RMizuguchi** [comment]
@balmma 
> But probably it would anyway be better to change the params syntax to something like &params=foo;bar;hello;world. IMHO this would be much clearer.

Ohh I see! Good a idea!
I try to this :-)

> No, certainly not. 

You are right.
When I removed AbstractScriptRunner, it seemed to be no problem. 
I don't know the reason...

**Comment by RaiMan** [comment]
@RMizuguchi 
@balmma 
I have to apologize, that I did not yet react, but I am a little bit stuck in revising the IDE implementation, which in parts is a mess and inconsistent (my god who the hell did that ;-).

ServerRunner surely is not a runner in the sense of the new runner implementation (as already mentioned above by @balmma).

It is intended to be a nice guy that runs on some "remote" machine and waits for requests to run scripts. So it is something like a remote commandline or a remote IDE-run-button. The implementation should allow, to simply write an url into the browser address field and press enter. 

To be open for additional features it should be named SikulixServer.

All SikuliX specifics should be implemented as a RESTful command structure with optional query strings for user parameters (script arguments):
`http://server/run/somescript?somevalue;someothervalue;`
Would run the script `somescript` with the user args `somevalue` `someothervalue`

There might be a default location for scripts applied when starting the server or some `set/scriptfolder/...` command.

... or you could write
`http://server/run/baseFolder/subFolder/subsubFolder/somescript`

which would be an absolute path in case nothing was said before about a default location or relative to the given default location. Other special cases like homefolder or windows-drive-letter are convenience features.

... as well as some html-pages or forms sent from the server, to support usage and result presentation (like the control box).

Other SikuliX options defined for the command line usage are not needed, since everything can be handled in the scripts itself as well.

Implementation details of your work @RMizuguchi I am not able to comment currently - see above.

Thanks for your both contribution.

**Comment by RMizuguchi** [comment]
@RaiMan 
Thank you for your comment.
I will also read your comment more deeply later.

There are Balmma's comments, and so I will work on making a better ServerRunner baseline.
So, please don't worry about the reviews.

I hope that your work goes well :-)

**Comment by balmma** [comment]
@RMizuguchi 
And please rename it to SikulixServer, remove the "extends AbstractScriptRunner" (including the unused constants in the beginning) and move it to the support package.

@RaiMan 
Just two points:
- Is it really a hard requirement to just enter the URL into the browser address bar and press enter? This way we are limited to simple GET requests. If we want to have a general purpose SikulixServer we should widen the verb range to GET, POST, PUT and DELETE (including OPTIONS for CORS). This will give a much nicer API. And there are many very lightweight REST clients available (e.g. Postman or the new Control Box) which makes the "simple address bar" requirement somewhat obsolete.
- You talk about running the SikulixServer on "remote" machines. IMHO we should start to think about threats like command injection and stuff. Especially the eval call is extremely dangerous in this manner.

**Comment by RaiMan** [comment]
@RMizuguchi 
Thank you. Come back at any time.

**Comment by RaiMan** [comment]
@balmma 

> Is it really a hard requirement to just enter the URL into the browser address bar and press enter? 

IMHO it should be possible to do that, if I only want to run a script, that is available on the system, that the server is running on.

Many other things are surely possible, that would need some client/frontend and can not be implemented with just GET.

With "remote" I simply meant, that I am using the server features on a machine, the server is not running on ;-)

As mentioned before: currently I am nothing more like some interested observer, who has some ideas, what the server should be able to do.

**Comment by RMizuguchi** [comment]
@RaiMan @balmma 
Please let me arrange the discussions till the now.

First, I would like to set the goal of this PR to the following. The purpose is to make a new starting point for SikulixServer. 

1. Implementation with Undertow
2. Add Control Box
3. Refactor startRunner
4. Refactor RunCommandHttpHandler
5. Update query string parsing
6. Rename ServerRunner to SikulixServer
7. Remove "extends AbstractScriptRunner" and Move it to the spport package
8. Remove Eval command (This feature does not currently work)

We will continue the discussion on the issue page for the following. I will create an issue with label "enhancement".
- SikulixServer's REST commands

Thank you.

**Comment by RaiMan** [comment]
@RMizuguchi 
Clapping hands: very good recap :-)

I copied the goal to the top.

When the commands issue is ready, we will add a link here.

**Comment by RMizuguchi** [comment]
@RaiMan 
Thanks :-)
I created the issue #130 . Please label the issue.

**Comment by RaiMan** [comment]
@RMizuguchi (thanks) and @balmma 
the feature discussion is open ;-)
issue #130

**Comment by RMizuguchi** [comment]
I completed the following. And git rebased.

- Refactor startRunner
- Refactor RunCommandHttpHandler
- Update query string parsing
- Rename ServerRunner to SikulixServer
- Remove "extends AbstractScriptRunner" and Move it to the support package
- Remove Eval command (This feature does not currently work)

**NOTE:** The syntax that gives run command args changed.
     ` "/run/script?args=arg1;arg2;arg3;"`
      This syntax is excellent in that the same arg can be set.

@balmma 
Thanks to your comment, this PR has become more better :-)

@RaiMan 
705c3f6 is what I tried to implement your TODO.
If it is wrong, please let know me ;-)

**Comment by RMizuguchi** [comment]
@RaiMan @balmma 
I posted my idea to #130 . Please look at it :-)

**Comment by RMizuguchi** [comment]
@RaiMan 
Did you find any problem with my commits?
Is there anything I can do?

**Comment by RaiMan** [comment]
No problems besides my lack of git knowledge ;-)
I wanted to have a dev branch for the SikulixServer, so I am able to merge, without triggering a new build on TravisCI.

With some detours through the git worlds I finally succeeded:
- your pull request #126 now only is in the branch dev-SX-Server

Further pull requests on this matter I will only pull into this dev branch, as well as my own commits/pushes to this matter.
When we say, the feature is ready, I will then merge it into master.

Thanks for your feedback.

**Comment by RMizuguchi** [comment]
Ok, understood. 
Thank you.

**Comment by RaiMan** [comment]
- started the SikulixServer
 - in browser: localhost:50001<enter>

... and Wooouuw the ControlBox smiled at me ;-)

I agree: this is how we can do it for the people, that just want to run and control remote script running.

Great thanks so far for your contribution.

**Comment by RMizuguchi** [comment]
I was relieved to hear your words.
Thank you very much. 
I will keep doing my best :-)

**Comment by RaiMan** [comment]
I switched off the -s option in the current build and added a note to the docs, that we are working on a complete revision of the feature.

When I checked the -s option in the current master build it had some strange behaviour with respect to the control box. If this can be fixed, we can switch it on again.

**Comment by RMizuguchi** [comment]
> When I checked the -s option in the current master build it had some strange behaviour with respect to the control box. 

Oh my gosh!
Please let me know the detail, I'll do the investigation.

**Comment by RaiMan** [comment]
Sorry for the buzz :-(
Checked again in the current master branch: works as documented.

I will now add the parameter handling for -g and -x to the dev branch:
 - RunTime::getGroups() will return a Map<String, String>
 - RunTime::getIPs will return a List<String>
for use in SikulixServer

**Comment by balmma** [comment]
Oh, before I forget it. Can we extend the -s option that we can define the listener ip and port? E. G. "- s 8080" or "-s 10.1.1.5:8080".

**Comment by balmma** [comment]
A good default might be localhost:50001. This way SikulixServer would only listen on localhost which would be a safe dwfault behaviour.

**Comment by balmma** [comment]
Sorry for posting this here. I'm on vacation and have my mobile phone only.

**Comment by RMizuguchi** [comment]
@RaiMan 
> Checked again in the current master branch: works as documented

Ok, no worries :-)

> I will now add the parameter handling for -g and -x to the dev branch

Thanks!!
BTW: I will start with the task queue implementation first.

@balmma 
You're right.
But, it is all right to set port only, isn't it? Because we have -x option.

And, have a nice vacation!

**Comment by RaiMan** [comment]
@RMizuguchi 
> BTW: I will start with the task queue implementation first.

agreed - good idea

@balmma & @RMizuguchi 
> -s startup option

I will add it to the wiki and respect it when adding/revising the startup.

I will add to RunTime:
 - getIP() returns the given startup IP (default localhost)
 - getPort() returns the given startup port (default 500001)

startup-option: -s [ [ip] [:port] ]

IMHO (might be wrong) the given IP is the one, the server listens on. So has nothing to do with the -x option, which lists the allowed client IP's.

**Comment by RMizuguchi** [comment]
> I will add to RunTime: ...

Thanks!!

> So has nothing to do with the -x option, which lists the allowed client IP's.

Yes.
But, when the listen IP address is localhost, I thought that the -x option did not work. 
For example, If start with `-s -x 10.1.1.5`, a reqeust from ip:10.1.1.5  is never accepted. This is because can access localhost from only localhost .

...But, I may be too worried.

**Comment by RaiMan** [comment]
@RMizuguchi 
When I start the server on machine A, it sits there and listens on port 50001 for incoming requests. Machine A has an IP of say 192.168.10.100 (in my private local net).
Then 
 - http://localhost:50001 and
 - http://192.168.10.100:50001
are equivalent on machine A.

Going to machine B in my private network, I can reach the server on machine A by
 - http://192.168.10.100:50001

Hence the server on machine A handles any incoming request on port 50001. Wether a request from outside machine A is granted or not, only depends on other measures taken in the network to secure the access to machineA:50001.

IMHO this would also be true for a SikuliX server running on a machine with an IP address reachable from anywhere in the world (usually supported by some DNS or whatever). 

An IP-whitelist given with the -x parameter would be a basic measure to secure the machine.

IMHO if a SikuliX server machine is reachable from the outside world, then the user (or netadmin) should have tools and workflows to secure his network (a reverse proxy is one of them) anyways.

**Comment by balmma** [comment]
We have some machines sitting in different networks. They have usually several IP addressed. Using "-s ip:port"  we can specify on which IP the server should listen. 0.0.0.0 means listen on all ips (which might probably be even a better default than 127.0.0.1). The Undertow listener most probably handles it in this way already.
This setting is quite common in server applications. Of course it's possible so limit the listening IP to localhost and that an IP from -x is no able to access the server. But - s is here to specify the target interface whereas -x is here to specify allowed source IPs. They have completely different intentions.

**Comment by RMizuguchi** [comment]
@RaiMan @balmma 

> if a SikuliX server machine is reachable from the outside world, then the user (or netadmin) should have tools and workflows to secure his network (a reverse proxy is one of them) anyways.

That's all right.

> Of course it's possible so limit the listening IP to localhost and that an IP from -x is no able to access the server.

This was what I care about.

But, I understood that -s and -x different intentions and agreed.

Thank you for your detailed explanation.

**Comment by balmma** [comment]
@RaiMan
Please make the default of -s 0.0.0.0:50001 instead of 127.0.0.1:50001. It seems to be the much more common default to listen to all available IPs. To ensure that we can only access the server from localhost we have -x.

**Comment by RaiMan** [comment]
@balmma 
already did it this way ;-) not yet pushed though.

**Comment by RaiMan** [comment]
@balmma & @RMizuguchi 
-s option revised and pushed (be aware: changes in SikulixServer startup!)

**Comment by balmma** [comment]
@RaiMan
Awesome :-) thank ya.

**Comment by RMizuguchi** [comment]
@RaiMan & @balmma 

> Please make the default of -s 0.0.0.0:50001 instead of 127.0.0.1:50001. It seems to be the much more common default to listen to all available IPs. To ensure that we can only access the server from localhost we have -x.

That makes total sense to me.

> -s option revised and pushed (be aware: changes in SikulixServer startup!)

That's you! Thanks :-)

**Pull request merged**
