### PR TITLE
Implement the remaining commands

### PR DESCRIPTION
**Pull request by RMizuguchi**
This PR has implementation of the follows commands:
- /scripts/:name/tasks, /groups/:name/scripts/:name/tasks
- /groups
- /groups/:name
- /resume
- /pause

Now all commands are implemented.
However, I feel that some commands need to be revised.
So I will post those revised in the next PR.

### CODE REVIEW

**Comment by RaiMan** [comment]
Thanks for your continuing efforts.

**Comment by RaiMan** [comment]
Now I finally found some time, to have a deeper look into your implementation: I am impressed.

Observations/comments (IMHO):
 - /scripts and /scripts/:name does not work either with or without /groups/:name
 - the init of the runners should be delegated to a thread like during startup of the IDE to get the server-ready faster
 - a task in the tasks history should show whether it is/was synchronous or asynchronous
 - the task-id should be a simple number beginning with 1 after server start (easier to use/remember)

Thanks again for your efforts.

**Comment by RMizuguchi** [comment]
@RaiMan

> Now I finally found some time, to have a deeper look into your implementation: I am impressed.

Thanks :-)

> /scripts and /scripts/:name does not work either with or without /groups/:name

Sorry. Yes, I had forgot these :p
Now I am doing these implementation.

> the init of the runners should be delegated to a thread like during startup of the IDE to get the server-ready faster

OK, I'll give it a try.

> a task in the tasks history should show whether it is/was synchronous or asynchronous

You are completely right. I agreed and will do it.

> the task-id should be a simple number beginning with 1 after server start (easier to use/remember)

OK, understood. I will do this too.

Thank you for your advices.

**Comment by RaiMan** [comment]
Thanks for confirmation and all the best

**Pull request merged**
