### PR TITLE
Providing a different path to users with a M1 MacBook

### PR DESCRIPTION
**Pull request by lukasdo**
Trying to fix issue #453.
The default installation folder of tesseract on a MacBook M1 is /opt/homebrew.

### CODE REVIEW

**Review by RaiMan — COMMENTED** [review]
Thanks for your input.
Is the os.arch property really unique, to detect macOS on M1?
As mentioned: I cannot check, due to lack M1 ;-)
Branch master is in early development state and should not be used for productive work.
Target for actual fixes is the branch release... (fix version 2.0.6). 
If you provide me with the relevant information I can implement a suitable fix myself. My approach would be to make this generally customisable through some option.

**Comment by RaiMan** [comment]
ok. thanks.

**Comment by lukasdo** [comment]
Okay took me a little bit longer than expected but os.arch could be used to distinguish an MacBook M1 from an intel MacBook. However, I guess we will run into new errors. Unfortunately I cannot get Sikuli to working on an M1 as I cannot compile it using java 8. On java 11 Sikuli crashes when a script gets executed.

Any thoughts?

**Comment by RaiMan** [comment]
If I understand right: You are trying to compile from a fork of this repo.

As already mentioned above: Branch master does not really work currently. And this will be so until later in July.

You have to checkout the branch release_2.0.x_21_04_29 and try with that.

This one still compiles with Java 8.

**Comment by lukasdo** [comment]
Hi I used the branch release_2.0.x_21_04_29 with Java 8 but I cannot build the jar because maven-compiler-plugin:3.8.1 is not found. Using Java 11 & 16 can be used to compile and create the Jar. However, as stated before when executing a simple script using java 11/16 the application crashes.

**Comment by RaiMan** [comment]
Please run the jar from Terminal as
`java -jar <path-to-jar> -v -c`
and attach the log output here.

**Comment by RaiMan** [comment]
no longer relevant

**Pull request closed without merging**
