### PR TITLE
Override equals for ScreenImage to perform a pixel comparison

### PR DESCRIPTION
**Pull request by balmma**
Relatively fast method to test if two ScreenImages are exactly the same. Can sometimes be convenient in scripts to just compare for example two screenshots like scr1.equals(scr2).

### CODE REVIEW

**Comment by RaiMan** [comment]
Very creative ;-) Thanks again.
I made a test - interesting result:
``` 
ScreenImage size: 1920 x 1200
ScreenImage.equals = true (109 msec)
Finder.find = 1.000000 (922 msec)
Finder.findChanges = 0 (47 msec)
```
This once again shows me, that there must still be some possibilities for better performance ;-)

**Comment by balmma** [comment]
The Finder.find measurement is quite a bit surprising to me. Theoretically this one should be almost as fast as Finder.findChanges (at least not slower by a factor of 20). Where is all the time lost? In the native code (matchTemplate)? While converting BufferedImages to Mat? Some JNI overhead? Will do some more measurements to hopefully identify the bottleneck.

**Comment by RaiMan** [comment]
Looking back on my test (did it on the Java level), I have to admit, that the find test contains a delay due to some "first-time-processing" (native load of OpenCV libs). I will check again.

**Comment by balmma** [comment]
I get similar results (although my native performance seems to be quite better than that of the Java VM):
```
ScreenImage.equals: 147.02
Finder.find: 354.1
Finder.findChanges: 16.9
```
My primary takeaway is that my equals function is really slow and that I shoud reimplement it using findChanges :-)

Will do further investigations to find out why find() is even slower.

**Comment by RaiMan** [comment]
When I changed from the old JNI based access with the intermediate Sikuli C++ code to the Java API wrapper available from OpenCV directly, I found, that the overall performance of the find features was similar. So I decided to go that way.

I think it makes sense, to track the timing down the line. I also will check the internal flow on things, that could be done better.

**Comment by RaiMan** [comment]
Quick test with Debug.on(3) (revealing the relevant timing infos):

case whole screen:
```
screen: 1920 * 1080 (Pixel 2025 KB)
image: 55 * 54
OpenCV time: 320 msec
overall: 380 msec
```
case Region:
```
region 300 * 300 (Pixel 87 KB)
same image
OpenCV time: 11 msec
overall: 18 msec
```

ratio screen/region: 23
calculated screen search time: 23 * 18 msec = 417 msec
real screen search time: 380 msec
This shows, that the search time simply grows linear with the number of pixels to check in the search region. 
Hence (in the docs and whenever I have a chance to say that): make the search region as small as possible.

**OpenCV time** is the CV.matchTemplate() time and the preparation of the result Mat when finished.
**overall includes** the conversion of BufferedImages to Mat beforehand.

Comment on findChanges(): this is only some intelligent Mat operations with the complete Mat's. No visiting of single pixels as with matchTemplate.

During the next days I will check OpenCV 4 and probably switch to it.

**Pull request merged**
