### PR TITLE
Abort script, JarRunner, SKLRunner, refactor isWrapper stuff

### PR DESCRIPTION
**Pull request by balmma**
This PR provides a basic script abort implementation.

The implementation is currently done for JythonRunner, JRubyRunner and JavaScriptRunner.

The IScriptRunner interface has three new methods:

- **isAbortSupported()** Can be overridden by a runner implementation to return true
- **abort()** Aborts the current running script execution. Runner implementation needs to implement doAbort()
- **isRunning()** Returns true if a runner is currently executing a script, false otherwise.

The abort is basically implemented by creating a new Thread for every script run and stops it upon abort().

Additionally, IScriptRunner.Options has a new field "timeout". This allows to automatically abort script execution after a given timeout has expired.

BTW: I had to touch SikulixRunner as well to propagate the abort() call to the real runner. There I noticed that @RaiMan added the .skl and .jar extensions and handled the runner detection with an if / else statement. Runner.getRunner() is already doing this. IMHO it would be much nicer to only define the .sikuli extension in SikulixRunner. When we have a .skl or .jar extension, then Runner.getRunner() will get either the JarRunner or SKLRunner (they can both extend SikulixRunner) which then can unpack the archive and call super.runScript(extractDir). It's basically the same but without the redundant Runner detection.

### CODE REVIEW

**Comment by balmma** [comment]
I you're OK with it I'm going to implement the SKLRunner and JARRunner next. Am I right that a .skl is just a zipped .sikuli folder? JarRunner is not limited to runnable SikuliX JARs is it? It it basically just a CMD call like "java -jar file.jar" and applicable to any executable JAR file?

**Comment by balmma** [comment]
Have just figured out that a JAR exported from SikuliX is not a real runnable JAR file. What is it?

**Comment by balmma** [comment]
BTW opening a .skl from within the IDE is broken even in current master.

**Comment by balmma** [comment]
OK, have just figured out that the JAR file is basically the same as a .skl but with the compiled python file. Other script types do not allow to export to a JAR file. Wasn't the exported jar file supposed to be self executable once?

**Comment by RaiMan** [comment]
> SKLRunner and JARRunner 

Everything you mentioned is right and ok.
In a first step I used the if-else construct, to  concentrate the "wrapping" runners in SikulixRunner. Wrapping means, the runner type can only be decided, by evaluating the content of a file or directory, to find out the script to run and the final runner type (networkrunner also has this problem).
And the given file/directory can be relative, in which case the base folder has to be decided (some current like group in the server, workdir, homefolder or whatever option)
This is only relevant, when running from command line, in the server or when stuff is loaded to the IDE, when started.
I was not really sure, where and how to implement the sapects of this two-step process.

The current master still has some quirks, that I will go after beginning on Monday. 

Until then I am offline due to a family event.

**Comment by balmma** [comment]
I've just noticed that it blocks when running with -r. Need some time to analyze and fix.

**Comment by balmma** [comment]
Will also add JarRunner and SklRunner in this PR. Have to refactor quite some of the wrapper stuff :-)

**Comment by RaiMan** [comment]
Sorry to be late - only slowly coming back to normal life (many things to arrange back in our home).

I have to admit, that I did not really have a final concept about the syntax/semantics of the -r option, when I started to revise Runner.runScripts.

The intermediate result was the idea with the check for a valid "inner script file".

After our lengthy discussion on SikulixServer, I like the idea to allow the group concept together with -r also.

- all relative file-specs are combined with the current base folder
- there is a default base folder if nothing else is specified (work or user)
- a file-spec without extension is being tested, wether either being a valid folder, a folder containing a valid script file or a valid script file in the current base folder
- if a file-spec is a valid folder not containing a valid script file, it becomes the default base folder (default group)
- if a relative file-spec starts with a valid group-name, it is translated
- a folder containing a valid script file, can be specified as script name

IMHO: this means, that the the evaluation of a file-spec has to be added to the can handle logic:
- valid folder with respect to the group collection (if no valid script, then no runner, but default base folder)
- a folder with a valid script

To support this, also with getRunner we have to use the options solution and add more features there.

**Comment by balmma** [comment]
> After our lengthy discussion on SikulixServer, I like the idea to allow the group concept together with -r also

IMHO we shouldn't make the -r option too overloaded. Just define either an absolute or a relative file (can also be a directory or a URL). Mixing it with groups might be too complicated and I don't see a real use case for it on the command line either. Let's keep it simple here.

**Comment by balmma** [comment]
Current status of this PR:

I've removed quite some directory / script / wrapper checking related code and moved some of it to the canHandle() of the following classes:

  - SKLRunner
  - NetworkRunner
  - SikulixRunner

SKLRunner and NetworkRunner are now fully working.

I think we have to postpone the JarRunner until we are able to export runnable JARs again. The JARs exportet by "Export as JAR" are not really suited to be executed by the Jython interpreter.

**Comment by RaiMan** [comment]
Ok, accepted (for now ;-).

Thanks again for your great input, very appreciated (also because you try to keep things near the ground and straight forward ;-)

I will merge it later (or should I wait?), have a look at it and feedback until later tomorrow.

**Comment by balmma** [comment]
Would probably be good to first have a look on it. I've just removed a lot of IMO redundant stuff.

**Comment by balmma** [comment]
@RMizuguchi 
After the merge we should also rebase the dev-SX-Server branch. Then you can use the abort stuff in your task list implementation.

**Comment by RMizuguchi** [comment]
Thanks @balmma 

> Then you can use the abort stuff in your task queue implementation.

Ok, understood.

BTW: 
I have high priority work now, and so SikulixServer work is running late. 
Also, now I'm organizing CommandHttpHandlers. This is because, I thought that it would be better to do the task queue implementation after doing organizing. (at first I was going to do the task queue implementation)
I will post a PR when it's convenient.

**Comment by balmma** [comment]
@RaiMan 
Good news: 
I have just figured out how to execute the compiled Jython class files as script. Will finish the JarRunner tomorrow as well.

**Comment by RaiMan** [comment]
> JarRunner

Good job :-)

Can you give me a tip:
Is it possible for me to create a branch from master (dev-runner) and merge this PR to the branch only?
I do not want to touch the master, before I have checked against the ideas I had the last weeks.

**Comment by balmma** [comment]
I think what you want to do is to checkout the PR code locally. Afterwards you can create a branch if you want to.

See https://help.github.com/en/articles/checking-out-pull-requests-locally

**Comment by balmma** [comment]
Or you could create a new remote branch from current master and then I can create PR to this branch. Or we put it to the SX-Server branch.

**Comment by balmma** [comment]
JarRunner seems to work for JARs exported by "Export as JAR".

**Comment by RaiMan** [comment]
@balmma 

> Or you could create a new remote branch from current master and then I can create a PR to this branch.

I decided to go this way. Please create the PR against the branch `dev-Runner`
Thank you for your support.

**Comment by balmma** [comment]
New PR #143 into dev-Runner.

**Pull request closed without merging**
