### PR TITLE
 First somewhat working preview version of recorder

### PR DESCRIPTION
**Pull request by balmma**
This is a very early preview version. It can already record very basic scripts, although a lot of stuff is not working yet.

### CODE REVIEW

**Comment by balmma** [comment]
@RaiMan 
Can you please rebase dev-Recorder? Then the PR will be less messy :-)

**Comment by balmma** [comment]
BTW: It took me quite a while to realize that the new branch is called dev-Recoder instead of dev-Recorder :-)

**Comment by RaiMan** [comment]
@balmma 
LOL - but Recoder isn't that bad also ;-) 

... a Recoder is a machine, that recodes something to another language: in this case your idea of a workflow into runnable code ;-)

Sorry, but I did not realise that at all, since after naming it at the start, I never had to type it again, but only click on some buttons/labels.

I did not find a way, to rename a branch!?
So any action needed?

**Comment by RaiMan** [comment]
I had a first look into the implementation and a first test: looks promising. 

> although a lot of stuff is not working yet.

Do you have some examples?

**Comment by balmma** [comment]
> So any action needed?

No :-)

> Do you have some examples?

Quite some:
- Double click
- Hover (e.g. in Menu)
- Drag
- Mouse wheel
- Right click
- Detection if an image is available right away or if it needs a wait
- Detection if an image is unique enough on the screen
- ...

**Comment by balmma** [comment]
Oh, and I've just noticed that it throws an NPE when one captures an image in a non Jython script. I've already fixed this locally. Will submit the fix with the next PR which will also implement some of the above examples.

**Comment by balmma** [comment]
Another thing:
What's the reason to have the OpenCV source code in this Repo instead of having it as a Maven dependency (in this case probably as a local Maven repository)?

**Comment by RaiMan** [comment]
Remembering my experiences with a JNativeHook-based recorder 2 or 3 years ago:

There are workflow actions, that can be evaluated directly: all click types, drag and drop, key strokes.

Other things like image capture and optimisation, intermediate wait's, unique image decision, hover, ... can be implemented with some assumptions, but might need more information about the user's intention. 

Since JNativeHook allows to consume events, it is possible to define some shortcuts, that can be used to get the user's intention in special situations. This could also be used, to pause and restart the recording.

Hover is a special case IMO: that the mouse does not move for a while during recording, does not mean anything in the first place - it depends on the user's intention, wether it should be part of the workflow or not.

About image and click point optimisation: To support the Pattern aspects (currently: concrete image, wanted similarity, click point, transparency mask) and a restricted search region we should have some ImageTool (an enhanced IDE Preview). This could be triggered by a shortcut during recording or could be used afterwords with the images in the recorded script. IMO a separate "project" though, since such a tool is also needed to better support non-SikuliX IDE's.

**Comment by RaiMan** [comment]
> What's the reason to have the OpenCV source code in this Repo

historical reason. When I started with the implementation of the SikuliX features based on the OpenCV Java API, it was easier to have the source code directly available in the project.

An additional challenge is the native Java API support: this is only available pre-built for Windows and has to be built for Mac and Linux separately on your own. ... and it is version specific.

Having the stuff in a local repo would surely be possible, but would make the TravisCI job more complex.

IMO not really something with priority.

**Comment by balmma** [comment]
> IMO not really something with priority.

Agreed, was just curious :-)

**Pull request merged**
