### PR TITLE
Java cleanup

### PR DESCRIPTION
**Pull request by jsa34**
Removed duplicates
Removed unnecessary castings
Removed unnecessary initialised values
Updated some dependencies
Stylised Java format over C++
Probably lots of things that need to be reviewed that may cause issues!

### CODE REVIEW

**Comment by jsa34** [comment]
Just trying to get a way in to reading/understanding the source code as I have just started using SikuliX and came across some suggestions for updates/stylising in Java code that I thought I would push

**Comment by jsa34** [comment]
Argh - rebasing nightmares.  I will close and raise pull requests for the individual clean up elements.

**Comment by RaiMan** [comment]
@jsa34 
Looks like much work and I appreciate it.
But for the future, it would save time and effort for both of us, if you would start with a small enhancement, that shows your goals. Then we can agree upon something and proceed.

In this case you have touched many files, that are either in packages, that are copied from other projects (different reasons, mostly for debugging) or are contributions, which I will not change in any "cosmetic" way. And there is code, that was not touched for years and needs more than only some "cosmetic" revisions.

the packages/folders: API/Support, jxgrabkey, py4java, android, guide
old code: FileManager, TransparentWindow, ...

> if ... else ... return

Those are mainly to have a debugging point before the return and should not get compacted.

> for-count loops to for-in loops

principally ok (the code is mainly from the times of Java <7 ;-)

> StringBuilder vs. String

principally ok, but cosmetics IMHO

> Objects.requireNonNull()

IMO only makes sense with a customised exception message and in cases, where the risk for null elements is >0

> xxxUtil, Runners, TextRecognizer, ...

there are some corrections, that might influence the behaviour - I will have a deeper look at it.

In general, it would be helpful to get such improvements as smaller entities, so they can be integrated step by step with some testing.

**Comment by jsa34** [comment]
Aha - good information to know, and makes sense.

I agree - it was only when I compared the diff and I realised what the diff was how much I had changed - apologies!  I will reevaluate and determine based on the information above if any of the changes are necessary/helpful!

Many thanks and thanks for the work on SikuliX - it is helping me greatly with a project I am working on, and would love to be able to contribute so just wanted to get familiar with the code :)

**Comment by RaiMan** [comment]
> would love to be able to contribute so just wanted to get familiar with the code :)

appreciated and accepted.

Since I am working with IntelliJ IDEA, I have to protect my eyes against all these yellow enhancement markers on the right edge of the editor window, to not get overloaded :-))
But your action encouraged me, to have a closer look at them, when I make changes to a file anyways. Thank you. All the best.

**Pull request closed without merging**
