### PR TITLE
Add task queue implementation

### PR DESCRIPTION
**Pull request by RMizuguchi**
This PR adds a task queue implementation.

Sorry for late:-( 
This work was trial and error.

### CODE REVIEW

**Comment by RMizuguchi** [comment]
@RaiMan 
Next, I will change the response to JSON.
I will use Jackson for my JSON library, and add dependency to pom.xml and deploy.xml.
Are there other xml files that I have to change?

**Comment by RaiMan** [comment]
--- about Jackson
in the IDE pom we already have these deps:
```
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-core</artifactId>
      <version>2.3.1</version>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
      <version>2.3.1</version>
    </dependency>
``` 

so it might be necessary, to have the Jackson deps in the API pom.
I will consolidate that, when needed.

**Comment by RaiMan** [comment]
> Sorry for late:-(

... don't worry, be happy :-))

**Comment by RaiMan** [comment]
Be aware: I will merge the master branch to dev-SX-Server latest tomorrow.

**Comment by RMizuguchi** [comment]
> in the IDE pom we already have these deps: ...
> so it might be necessary, to have the Jackson deps in the API pom.
> I will consolidate that, when needed.

I understood.

> ... don't worry, be happy :-))

Thank you :-)

> Be aware: I will merge the master branch to dev-SX-Server latest tomorrow.

Ok, thanks.

**Pull request merged**
