### PR TITLE
Detect current keyboard layout and use it for type (on Windows)

### PR DESCRIPTION
**Pull request by balmma**
The SikuliX type function only reliably works with the US keyboard layout .

This due to the fact that the key code combinations are hard coded in the Key class. And even if the key combinations wouldn't be hard coded, AWT Robot can't handle key codes for unicode characters (e.g. öäü on German keyboards) at all.

The new implementation bypasses AWT Robot entirely for key presses and key releases on Windows (other OSes still use AWT Robot with the default behaviour and the hard coded US layout). 

It automatically builds a key mapping based on the currently selected locale (similar to the native implementation in https://github.com/frohoff/jdk8u-jdk/blob/master/src/windows/native/sun/windows/awt_Component.cpp, but with full Unicode support). Then it uses this mapping to get the key code for a character and uses the Windows API to simulate a key press / release.

### CODE REVIEW

**Comment by RaiMan** [comment]
Looks impressive and promising ;-)

Works with Win 7 and later or any known restrictions??

Any risk to publish it not tested from my side?

**Comment by balmma** [comment]
I've actually tested it on Win 7 and Win 10 with some western keyboard layouts. They seem to work very well.
I've also tested some eastern layouts like Russian and Bengali and they seem to work as well. I had no luck with Chinese or Japanese layouts though. But this is probably because I don't know how to use them properly :-)
A risky point is that some users may already have implemented some workarounds to type characters on non US layouts. This change might break those workarounds.

**Comment by RaiMan** [comment]
great thanks for the feedback and your work - highly appreciated.

Possible to add a Settings attribute (TypeOnEveryKeyBoardLayout :-) with default = true), were one could switch off this new handling?

**Comment by balmma** [comment]
Amazing idea. Done :-)

**Comment by RaiMan** [comment]
LOL: Together we are genius ;-)

**Comment by RaiMan** [comment]
I will add a comment to the docs. Great Thanks.

**Comment by balmma** [comment]
Just as a side note:
You have the following code snippet in region.html:

`paste("йцуке") # will end up in some garbage`
`paste(unicd("йцуке")) # will work as expected`

Isn't it simpler to just use a Unicode string literal like:
`paste(u"йцуке")`
`type(u"йцуке")`
`App.focus(u"йцуке")`

**Comment by RaiMan** [comment]
Thanks for the hints. This is from the times before Jython 2.7, which now has the u"" strings.
I will revise the docs on unicode/UTF-8

... and of course it is simpler and much more pythonic ;-)

**Comment by RaiMan** [comment]
Motivated by a request to make the following key available:
``VK_APPS  0x5D | Applications key (Natural keyboard)``
sometimes also called menu key  (right side between win-key and strg/control), I ran into troubles.

Besides having problems, to fully understand your implementation ;-), I had to realize that these are not working:
``type(Key.WIN)``
``type("r", Key.WIN)``
... one has to switch off your implementation.

My idea with the menu key was to add a ``Key.WIN_APPS``, but since there is no Java key code, I am not sure where I have to add what.

Please help.

**Comment by balmma** [comment]
OK, shouldn't be too much of an issue. Will have a look at it. I think the VK code you are looking for is VK_RMENU.

**Comment by balmma** [comment]
Additionally I've to map the WIN key code. AWT and Windows codes are not fully compatible. Shall we use the KeyEvent.VK_ALT_GRAPH key for right alt? This one we have to map to VK_RMENU for Windows. Have you already detected other non working AWT codes?

**Comment by RaiMan** [comment]
I just checked: the key is already there in the awt-mapping: CONTEXT -> VK_CONTEXT_MENU
... but it only works with the Settings option switched off :-(

KeyEvent.VK_ALT_GRAPH is there, but only as modifier key (needed as normal key? I guess no)

**Comment by balmma** [comment]
Allright, that means that I have to map VK_CONTEXT_MENU to VK_RMENU and VK_WIN to VK_LWIN. I'm going to implement it this evening, not a big deal :-)

**Comment by RaiMan** [comment]
Thanks, but no hurry - take your time.

I guess if you get that working, I will have a chance to understand the implementation and handle future issues myself.

**Comment by balmma** [comment]
Oh, and I've to handle ALTGR in RobotDesktop's pressModifiers...
No worries, for me it's quite fun to work on something like this. It's kind of a puzzle :-)

**Comment by RaiMan** [comment]
Ok, then have a funny evening and great thanks :-)

**Pull request merged**
