### PR TITLE
fixed: SikulixServer: change the way of adding HttpListener depending on the given IP

### PR DESCRIPTION
**Pull request by RMizuguchi**
If start with `-s` only, `addHttpListener(port, "localhost")` and `addHttpListener(port, "0.0.0.0")`  overlap and start fails.
This PR is fix it.

### CODE REVIEW

**Comment by RMizuguchi** [comment]
This has already been fixed, but I think we should always have access to localhost.
Would you like me rebase and fix the conflict?

**Comment by RMizuguchi** [comment]
I rebased.
It's late at night here, so I'll finish work today.

**Comment by RaiMan** [comment]
As mentioned: the default now is 0.0.0.0 which includes listening to loacalhost (see comments @balmma )

**Comment by balmma** [comment]
IMHO it's a legit question wether or not the server should always be accessible on localhost, even if we set a specific IP using the -s option. Apache for examle defaults to 0.0.0.0 and listen to all available IPs. As soon as you define one Listen directive, it listens only on the defined IP. Since Apache allows to define multiple Listen directives it's possible to add "Listen 127.0.0.1" and listen to localhost as well. In our configuration we only have one listener IP to configure. This means we either have to use 0.0.0.0 or 127.0.0.1 to have local connectivity. As soon as we define a specific IP we have no way to listen to localhost as well. I vote for always bind to localhost because it doesn't really hurt, localhost is just a special IP and it might sometimes be quite convenient

**Comment by RMizuguchi** [comment]
@balmma 
Thank you for your follow.

@RaiMan 
I will not delete this branch yet, so I am glad if you will consider this again.

**Comment by RaiMan** [comment]
@balmma & @RMizuguchi 
Fully agreed looking at the design:
 - the server should always be accessible locally, no matter what IP was given with the -s option

@RMizuguchi 
The problem is the implementation.

IMHO we should always have the server listening to  0.0.0.0 (which as I understand includes localhost/127.0.0.1).
If the IP given with -s does not conflict with (or is included in) 0.0.0.0. then it is also added. Otherwise it is ignored.

so IMHO the logic should be:

```
Undertow.Builder builder= Undertow.builder().setHandler(resource);
builder.addHttpListener(port, "0.0.0.0")
if (givenIPdoesNotConflict) //pseudo;-)
    builder.addHttpListener(port, ipAddr);
endif //pseudo
server = builder.build();
```
... but I do not know, wether using the same port is a problem.

**Comment by balmma** [comment]
0.0.0.0 means "listen to all available IPs" (including 127.0.0.1). This is the default for the -s option.

As soon as we have a different IP specified, we should not any longer listen to 0.0.0.0 but to the specified IP and 127.0.0.1. If the specified IP is 127.0.0.1 we only have to listen to 127.0.0.1 once.

We are perfectly allowed to listen to the same port on different ips.

Pseudo code something like:

if(serverIP == "0.0.0.0")
  Listen 0.0.0.0
else if (serverIP == "127.0.0.1")
  Listen 127.0.0.1
else
  Listen 127.0.0.1
  Listen serverIP

**Comment by balmma** [comment]
BTW all available IPs conflict with 0.0.0.0 on the same port :-)

**Comment by RaiMan** [comment]
Thanks for the explanation. Makes sense.

**Comment by RMizuguchi** [comment]
@RaiMan & @balmma 

I'm sorry to reply late.
Also, thank you for your consideration again.

> if(serverIP == "0.0.0.0")
> Listen 0.0.0.0
> else if (serverIP == "127.0.0.1")
> Listen 127.0.0.1
> else
> Listen 127.0.0.1
> Listen serverIP

My code should be equivalent to this.

**Comment by RaiMan** [comment]
... but I am still confused about the following (given IP is 0.0.0.0):

```
...
            .addHttpListener(port, "localhost")
            .addHttpListener(port, ipAddr)
...
```

 - works on Mac
 - crashes on Windows saying `IP already in use`

... but this might simply a weak implementation on Mac.

**Comment by balmma** [comment]
Well, no idea why this is working on Mac. Question is: Is it really working or is it simply not throwing an exception? :-)

**Comment by RaiMan** [comment]
It simply worked on same machine (localhost, 0.0.0.0, IP) and from other machines in my LAN using the IP.

**Comment by balmma** [comment]
Agree

**Comment by balmma** [comment]
We should probably also add the corresponding IPv6 equivalents:

"0.0.0.0" -> "::"  listen to all available IPv6 IPs in case no specific IP is defined 
"127.0.0.1" -> "::1" always bind to IPv6 localhost as well.

**Comment by balmma** [comment]
-s option parsing should be implemented in a way that it can also handle IPv6 addreesses:
```
 if (listenAt[0].contains(":")) {
          listenAt = listenAt[0].split(":");
        }
        serverIP = listenAt[0].trim();
        if (listenAt.length > 1) {
          try {
            serverPort = Integer.parseInt(listenAt[1].trim());
          } catch (NumberFormatException e) {
          }
        }
      }
```
This implementation assumes that the port is the second entry in the split Array. Considering the format of an IPv6 address (e.g. 2001:0db8:85a3:0000:0000:8a2e:0370:7334), we have to take the last entry as port and join the head of the array with : to get the address:

**Comment by balmma** [comment]
Oh, a new idea just slipped into my mind :-)

Would it be even better to allow multiple -s options to be defined? This way we could avoid the default binding to 127.0.0.1 and allow the user to do this explicitly.

e.g.
-s -s 10.1.1.23:50001 -> binds to 10.1.1.23 only
-s 127.0.0.1:50001 -s 10.1.1.23:50001 -> binds to 127.0.0.1 and 10.1.1.23
-s -> binds to 0.0.0.0

**Comment by RMizuguchi** [comment]
@balmma 
Thank you for your idea :-)
But, for a while, I would like to fix Handlers preferentially.

**Comment by RaiMan** [comment]
@balmma 
Ok, IPv6 is not in my daily experiences ;-)
Will try to implement it.
I read the relevant Wiki entry and found this for the browser addressline:
[2001:0db8:85a3:0000:0000:8a2e:0370:7334]:port
Might be an idea, to expect this with -s for IPv6 

About -s parameter we should be consequent:
If it makes sense, to specify more than one ip:port, then we should use the same as with -g and -x and expect a file spec for more than one IP:port.
... and with the *always listen on localhost* we should leave it as is (if it does not make harm in any situation).

**Comment by RaiMan** [comment]
@balmma 
> We should probably also add the corresponding IPv6 equivalents:
"0.0.0.0" -> "::" listen to all available IPv6 IPs in case no specific IP is defined
"127.0.0.1" -> "::1" always bind to IPv6 localhost as well.

Am I right: has to be handled in the SikulixServer (has nothing to do with parameter handling).

**Comment by balmma** [comment]
@RaiMan 
> Am I right: has to be handled in the SikulixServer

Exactly, pseudo code should be something like this:
```
if(serverIP == "0.0.0.0" || serverIp == "::")
  Listen "0.0.0.0"
  Listen "::"
else if (serverIP == "127.0.0.1" || serverIp == "::1")
  Listen "127.0.0.1"
  Listen "::1"
else
  Listen "127.0.0.1"
  Listen "::1"
  Listen serverIP
```

**Comment by balmma** [comment]
@RaiMan 
> then we should use the same as with -g and -

You are right, completely agree.

> [2001:0db8:85a3:0000:0000:8a2e:0370:7334]:port

Yes, this is the correct notation and should be handled by the options parser.

**Comment by RaiMan** [comment]
@balmma 
ok, will do so.

I added some examples and the IPv6 stuff to the Wiki.

> about one value only and no : (-s foobar)

Suggestion: 
if foobar can be evaluated to int, then it is taken as port, otherwise as IP

**Comment by balmma** [comment]
> if foobar can be evaluated to int, then it is taken as port, otherwise as IP
A bit too smart-ass for my taste ;-) IMHO a single value should always be interpreted as port and take 0.0.0.0 as IP. Defining the IP only (especially since we are using a very arbitrary port) does hardly make any sense at all to me. But feel free to implement it this way, won't hurt much either :-)

**Comment by RaiMan** [comment]
@balmma 
>  IMHO a single value should always be interpreted as port

ok, already pushed the commit. 
Will revise it tomorrow this way.

**Comment by balmma** [comment]
@RaiMan
You can also leave it as it is. It's not a bad solution. Just a bit too clever ;-)

**Comment by balmma** [comment]
Had some time to do some tests with undertow. It seems to already handle this IPv6 stuff internally. When I define -s 127.0.0.1:50001 the server is also available on [::1]:50001 and if I define 0.0.0.0:50001 the server also responds to IPv6 addresses as well. This also works the other way round. Means that we don't have to handle this stuff in our code (except the option parsing which seems to work now).

**Comment by RaiMan** [comment]
@balmma 
> You can also leave it as it is. It's not a bad solution. Just a bit too clever ;-)

LOL, just clever enough, to let a single string be a file-spec, if it cannot be converted to a number.
but this insight only hit me this morning ;-)

**Comment by balmma** [comment]
OK, not that clever though :-)

**Comment by balmma** [comment]
Wow, have just figured out that the IPv6 stuff seems to be handled not by Undertow but by the OS. On Linux if I define "-s 127.0.0.1:50001" I can also access the server on [::1]:50001. On MacOs only 127.0.0.1:50001 works. If I define "-s [::1]:50001" I can also use 127.0.0.1 on Linux on mac only [::1] works. On Linux I even get a BindException if I try to add 0.0.0.0 and [::] togheter. Strange enough adding 127.0.0.1 and [::1] together seems to work.
My suggestion is not trying to handle the IPv6 stuff in our code. Let's stick to the IPv4 bindings and let the OS decide what to do with it.

**Comment by balmma** [comment]
> not trying to handle the IPv6 stuff in our code
Of course I mean the SikulixServer addHandler part. -s option parsing must still be able to handle IPv6 addresses.

**Comment by RaiMan** [comment]
evaluation of the -s option now handles a given file containing IP:port lines:
 - the stuff is stored in a `Map<String, Integer> serverListenAt`.
 - the values from the last line read are in `serverIP` and `serverPort`
 - a given port is the default port for the following lines having only an IP

currently the server still starts with `serverIP: serverPort` and ignores `serverListenAt`

**Comment by balmma** [comment]
> the stuff is stored in a Map<String, Integer> serverListenAt

Does this imply that we can specify only one port per IP? Last entry wins?

**Comment by balmma** [comment]
> and the server starts with 192.168.2.100:50002

Don't get the logic behind it. Why is 50002 also applied to 192.168.2.100? Shouldn't every line stand for it's own?

evaluates to:
```
serverListenAt:
0.0.0.0:50002
192.168.2.100:50001
```

**Comment by RaiMan** [comment]
> Shouldn't every line be evaluated on it's own?

changed the logic (and the comment above), so it does now.

> Does this imply that we can specify only one port per IP?

Currently yes. Is more than one port per IP needed?

**Comment by balmma** [comment]
> Is more than one port per IP needed?

Probably not, it's just a limitation one has to be aware of. What about having a List<Pair<String,Integer>>?

**Comment by RaiMan** [comment]
> What about having a List<Pair<String,Integer>>?

agreed - done also in comment above.

**Pull request closed without merging**
