### PR TITLE
Set SikuliX icon to main IDE frame

### PR DESCRIPTION
**Pull request by balmma**
Very minor PR just to see the SikuliX icon instead of the default Java one on the main IDE frame :-)

### CODE REVIEW

**Comment by RaiMan** [comment]
This fix does not work on Mac (not tested on Linux).
Any idea?

**Comment by balmma** [comment]
It works on Linux and Windows, don't have a Mac at hand :-(

**Comment by RaiMan** [comment]
Ok, thanks. Will dive into the Mac djungle :-)

**Comment by balmma** [comment]
Should be solved in PR #138

**Pull request merged**
