### PR TITLE
Revise handlers

### PR DESCRIPTION
**Pull request by RMizuguchi**
In this PR, I revised Handlers to make the next implementation easy.
I also made the following changes:
- Removed: /start, /startp, /exit, /images, /run
- Added: /scripts/:name/run
- Added: /groups/:name/scrips/:name/run

### CODE REVIEW

**Comment by RMizuguchi** [comment]
I found a bug on the way and it took a long time to investigate.
The bug is that RobotRunner.doInit () from SikulixServer fails with "ImportError: can not import name BytesIO".
It fails because, if `import io` is described in a Python package like robot, Jython import process imports "io" from io.undertow as a Java package before io package on sys.path.

If modify RobotRunner.doInit () as follows, startup will succeed.
`this.getInterpreter (). exec (" import io; import robot ");`
But I'm not sure if this is a good solution.
I tried to SikulixServer.run() in another thread and separate ClassLoader, but it didn't work well.
Do you know any good solution?

**Comment by balmma** [comment]
@RMizuguchi 
this.getInterpreter().exec("import io; import robot");
> But I'm not sure if this is a good solution.

I don't think that this will hurt, but I've no idea WHY this works :-) Why is it importing the right  module when importing it before robot? Does robot somehow mangling the sys.path?

**Comment by RMizuguchi** [comment]
@balmma 

> WHY this works :-)

Looking at the source code, Jython's import process imports in the following order:

1. From imported(loaded) modules
2. For import from within the package: From within the package
    Otherwise: From sys.path
3. From Java package
4. For import from within the package: Remove the package and redo from 1 again
    Otherwise: Import Error

This bug is caused by false detection of io.undertow package by 3 after `import io` in the robot package can not be found by 2.
Therefore, `import io` before` import robot` will be found at 1 and will succeed.

> I don't think that this will hurt

Yes. Certainly, RobotRunner will not hurt. I was worried about JythonRunner.
Some user Python scripts thought that similar `import io` error might occur in SikulixServer, and was looking for other solutions.
It may be good to add `import io` to JythonRunner.doInit(), but it may not work correctly if the package has its own io package.
Am I over thinking it?

**Comment by balmma** [comment]
>  I was worried about JythonRunner

Oops, you are completely right. This might be problematic indeed.

> This bug is caused by false detection of io.undertow package by 3 after import io in the robot package can not be found by 2.

Still don't get why it can't find "io" at 2. in the robot package. I mean, the Jython lib is definitely in sys.path.

**Comment by balmma** [comment]
Strange. I've just tried to do the "import io" in another module placed in site-packages and this seems to work. So it seems that this is not a general Jython but rather a robot problem.

**Comment by RMizuguchi** [comment]
> Still don't get why it can't find "io" at 2. in the robot package. I mean, the Jython lib is definitely in sys.path.

That's right. Jython lib is included in sys.path.
However, Jython is not looking sys.path from under certain conditions.

Correctly, `import io` is described in robot.utils/etreewrapper.py.
And Jython(at processing 2) ignores sys.path and searches for "io" package **only within robot.utils**. It is not found because robot.utils does not have "io" package. 
Then Jython does not search in sys.path but in Java Package. (at processing 3)

> Strange. I've just tried to do the "import io" in another module placed in site-packages and this seems to work. 

Sorry. I have one more report.

Also, the pattern that is causing the problem seems to be when import io from a subpackage (a package in a package).
The reason why this is the case only for subpackages has not been examined.

If the site-packages you tried has subpackage and import io from the subpackage, I may be wrong.

**Comment by RMizuguchi** [comment]
**BTW:**
Currently, JythonRunner and RobotRunner use the same PythonInterpreter. 
So, if import "io" to one side, will be import "io" to both.

**Comment by balmma** [comment]
> Also, the pattern that is causing the problem seems to be when import io from a subpackage

Yes, quite a bit a strange behavior.

I would say we should be pretty safe by adding 

`interpreter.exec("import io");`

to JythonRunner$doInit() next to

`interpreter.exec("import sys");`

**Comment by balmma** [comment]
@RMizuguchi 
Would it be possible for you to rebase to the dev-Runner branch? Merging would be much easier afterwards.

**Comment by balmma** [comment]
@RMizuguchi 
Would also be nice to add a comment in JythonRunner why we import io there :-)

**Comment by balmma** [comment]
@RMizuguchi 
Better wait with rebase until PR #148 is merged.

**Comment by RMizuguchi** [comment]
@balmma 

> I would say we should be pretty safe by adding ...
> Would also be nice to add a comment in JythonRunner why we import io there :-)

Yes. There are few cases where site-package's subpackage has its own io package, and this will work well in most cases.
Thank you :-)

>Would it be possible for you to rebase to the dev-Runner branch? Merging would be much easier afterwards.

It is rebase with dev-runner and doing PR to dev-SX-Server, right?

>Better wait with rebase until PR #148 is merged.

Ok :-)

**Comment by balmma** [comment]
> It is rebase with dev-runner and doing PR to dev-SX-Server

I would say you should be able to just rebase your revise-handlers branch and push again. New commits should automatically land in this PR.

**Comment by RMizuguchi** [comment]
> I would say you should be able to just rebase your revise-handlers branch and push again. New commits should automatically land in this PR.

Ok, understood.

**Pull request merged**
