### PR TITLE
Make Sikulix icon working on MacOS as well

### PR DESCRIPTION
**Pull request by balmma**
image

### CODE REVIEW

**Comment by balmma** [comment]
Close again, have to refactor this stuff quite a bit.

**Comment by balmma** [comment]
Refactored :-)

**Comment by RaiMan** [comment]
Thanks. Good job ;-)

**Comment by balmma** [comment]
Yes, was quite a bit more complicated than expected. So much about platform independence :-)

**Comment by balmma** [comment]
To be fair, it would have been much simpler without the Java 8 backwards compatibility :-)

**Pull request merged**
