### PR TITLE
Change type of similarity to double in IDE to be compatible with API

### PR DESCRIPTION
**Pull request by balmma**
To avoid the float to double conversion issues.

### CODE REVIEW

**Comment by balmma** [comment]
Oh, I've just discovered another issue when moving the slider. Will add another commit shortly.

**Comment by balmma** [comment]
Should be fine now.

**Comment by balmma** [comment]
Still some more floats.

**Comment by balmma** [comment]
Need just another iteration.

**Comment by RaiMan** [comment]
Sorry for not being fast enough to take this float-picking over.
Surely a work that should be done by slaves and not by masters ;-)
Thanks anyways.

**Comment by balmma** [comment]
Uff, hope that I have buried all remains now :-)

**Comment by balmma** [comment]
And I coudn't resist to replace those Double.valueOf, Float.valueOf and Integer.valueOf with the corresponding parse methods. valueOf returns an object which just gets directly unboxed when assigned to the variables.

**Pull request merged**
