### PR TITLE
Update ServerRunner

### PR DESCRIPTION
**Pull request by RMizuguchi**
Hello,

Since I want to contribute to the project, I made a new feature.
I named this feature "SikuliX-Server Control Box". It can send commands from the browser GUI page to SikuliX ServerRunner.
After launch ServerRunner, access to http://localhost:50001/ by the browser, can use it.

SikuliX is very useful for our team's duty. And, I especially use ServerRunner, I like it.
So, I made this feature to make ServerRunner easier to use and I hope it come into use more.

Also, this pull request include some fiexed.

Please let me know, if there are any issues.

Thank you.

### CODE REVIEW

**Comment by RaiMan** [comment]
Wooouuuw :-) great idea.

I will have a look at it.

Currently I have blocked myself against merging pull requests, since I have started to revise the IDE and missed to do that in an extra branch. I guess next week I am ready to merge and build again.

Always welcome.

**Comment by RMizuguchi** [comment]
Thank you.

> I guess next week I am ready to merge and build again.

OK, understood.

**Comment by balmma** [comment]
Just as an idea:
The ServerRunner implements a very basic HTTP Server on it's own. Wouldn't it be much more future proof (and in the end much simpler) to use an already well established HTTP Server implementation (Jetty might be a good candidate)?

**Comment by RaiMan** [comment]
@balmma 
Surely right :-)

But Jetty IMHO is not the right candidate for SikuliX (too big ;-)
... or am I wrong?

My favorite currently is http://undertow.io.

… but a more generic server solution currently has low priority on my list.

But feel free, to make suggestions or even some basic implementation example.

**Comment by RMizuguchi** [comment]
@RaiMan @balmma 
That's a good idea.

The current basic implementation can blocks concurrent execution of script runner. I think that this is very important.
Have to consider this when replace it by Java Servlet.

It is interesting, so I will try it while comparing Jetty and Undertow.

**Comment by balmma** [comment]
@RaiMan 
Yes, Jetty would most probably be an overerkill. It was just the first thing that jumped into my mind :-)

@RMizuguchi 
Would really love to see an more generic implemention of the ServerRunner.

**Comment by RMizuguchi** [comment]
Sorry for the confusing explanation.

Don't worry. I think too that it should be a single(sequential) script execution. 
Also, I am planning to implement by Undertow BlockingHandler.

Thank you.

**Comment by RaiMan** [comment]
@balmma 
> According to parallel script execution.

... on the same machine is principally not possible and does not make sense from the viewpoint of SikuliX: the different scripts are constantly steeling each other mouse, keyboard and screen foreground :-)

But having some jobqueue or even timed execution is surely a nice-to-have.

**Comment by RMizuguchi** [comment]
Sorry for the confusing explanation.

Don't worry. I think too that it should be a single(sequential) script execution. 
Also, I am planning to implement by Undertow BlockingHandler.

Thank you.

**Comment by RMizuguchi** [comment]
@RaiMan 
I became have a clear idea how implementation by Undertow, and so I am thinking of dropping this pull request and proposal new pull request.
If you are not merging, I will drop this pull request immediately.

Do you have a problem with this?

**Comment by RaiMan** [comment]
@RMizuguchi 
Please post your pull request.
I will manage ;-)

**Comment by RMizuguchi** [comment]
@RaiMan 
Yes, sir :-)
I will post another new pull request in this week' time.

**Comment by RaiMan** [comment]
@RMizuguchi 
Take your time, I am a bit behind anyways.
Thanks for your efforts.

**Comment by RMizuguchi** [comment]
This PR is no longer required. So, I will close this.
(New PR is #126 )

**Pull request closed without merging**
